### ISSUE TITLE
（use arcface model）  AttributeError: 'NoneType' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by ruyijidan** [RizhaoCai/PyTorch_ONNX_TensorRT#1]
show:Completed parsing of ONNX file
but when

    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

I guess my onnx model maybe have some problem,I am trying check the pth2onnx..

**Comment by RizhaoCai** [comment]
Hello. Sorry for the late response.
It could be the problem that you do not generate an ONNX model which could accommodate with the TensorRT. Could you share more information?

**Comment by RizhaoCai** [comment]
> show:Completed parsing of ONNX file
> but when
> 
> ```
> f.write(engine.serialize())
> ```
> 
> AttributeError: 'NoneType' object has no attribute 'serialize'
> 
> I guess my onnx model maybe have some problem,I am trying check the pth2onnx..

Hello. Sorry for the late response.
It could be the problem that you do not generate an ONNX model which could accommodate with the TensorRT. Could you share more information?

**Comment by ruyijidan** [comment]
Thank you for reply!
I have konw the issue is when onnx2tensorrt tensorrt does not support Prelu,So the engine is None.Tensorrt also have no output.

**Comment by RizhaoCai** [comment]
> Thank you for reply!
> I have konw the issue is when onnx2tensorrt tensorrt does not support Prelu,So the engine is None.Tensorrt also have no output.

I think it should be the problem of the onnx exporter instead of the tensorrt.
