### ISSUE TITLE
Run batch size with inputs[1].host

### ISSUE THREAD

**Issue by tuongtranngoc** [RizhaoCai/PyTorch_ONNX_TensorRT#10]
Hi, everyone
I define batch_size_max = 4 and input size onnx= 2 to run batch_size = 2 for model trt
When i convert model that Error show "list index out of range" in inputs[1].host
That mean inputs only have one elements.
How to fix when i want to run batch size > 1

**Comment by RizhaoCai** [comment]
Hi @NgTuong ,

If you have a batch of data X, of which the size is [b, c, h, w], inputs[1] does not mean the second element of the batch, i.e. X[1].

To be more specific, if your network has the below forward function

```python
def forward(self, input1, input2):
    ....
```

inputs[1] represents input2.

**Comment by RizhaoCai** [comment]
Hi @NgTuong 

Please take a look at  https://github.com/NVIDIA/TensorRT/issues/842#issuecomment-769567750
and [dynamic_shape_example](https://github.com/RizhaoCai/PyTorch_ONNX_TensorRT/blob/master/dynamic_shape_example.py)
