### ISSUE TITLE
Int8 implementation

### ISSUE THREAD

**Issue by andcarnivorous** [RizhaoCai/PyTorch_ONNX_TensorRT#2]
Hi! Any idea or resources on how to implement the Int8? The documentation from Nvidia is too minimal to get how it is supposed to work. They mention creating two objects, but who knows from which classes and how.

**Comment by RizhaoCai** [comment]
> Hi! Any idea or resources on how to implement the Int8? The documentation from Nvidia is too minimal to get how it is supposed to work. They mention creating two objects, but who knows from which classes and how.

Recently, I have been busy on writing a CVPR manuscript. I will work on the INT8 implementation after the submission.

**Comment by RizhaoCai** [comment]
@andcarnivorous 

Hey, sorry for the delay. I got too busy with other stuff. 
I just upload the [int8 example](https://github.com/RizhaoCai/PyTorch_ONNX_TensorRT/blob/master/trt_int8_demo.py). 
Thanks for attention.
