### ISSUE TITLE
error:create_execution_context 

### ISSUE THREAD

**Issue by wxy1234567** [RizhaoCai/PyTorch_ONNX_TensorRT#3]
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

**Comment by RizhaoCai** [comment]
Sorry for late response. This could be due to that you failed to create an engine and thus 'None' was returned

**Comment by RizhaoCai** [comment]
> AttributeError: 'NoneType' object has no attribute 'create_execution_context'

Sorry for late response. This could be due to that you failed to create an engine and thus 'None' was returned. 

1) Please check info printed on the screen and see what errors happened when building an engine.
2) Delete the saved engine file for that it could be a broken engine

**Comment by zwqnju** [comment]
I think that I fix this issue. I fork @RizhaoCai 's project. My version is here: https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb
I just modifed a few lines.

**Comment by longnanxi** [comment]
> 我认为我已解决此问题。我分叉@RizhaoCai的项目。我的版本在这里：[https](https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb) : [//github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb](https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb)
> 我刚刚修改了几行。

hello  请问您cudnn的版本是什么？

**Comment by zwqnju** [comment]
> > 我认为我已解决此问题。我分叉@RizhaoCai的项目。我的版本在这里：[https](https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb) : [//github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb](https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb)
> > 我刚刚修改了几行。
> 
> hello 请问您cudnn的版本是什么？

7.6.4
But I don't think that it matters.

**Comment by longnanxi** [comment]
> > > 我认为我已解决此问题。我分叉@RizhaoCai的项目。我的版本在这里：[https](https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb) : [//github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb](https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb)
> > > 我刚刚修改了几行。
> > 
> > 
> > hello 请问您cudnn的版本是什么？
> 
> 7.6.4
> But I don't think that it matters.

tensorrt版本必须是7吗？

**Comment by zwqnju** [comment]
> > > > 我认为我已解决此问题。我分叉@RizhaoCai的项目。我的版本在这里：[https](https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb) : [//github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb](https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb)
> > > > 我刚刚修改了几行。
> > > 
> > > 
> > > hello 请问您cudnn的版本是什么？
> > 
> > 
> > 7.6.4
> > But I don't think that it matters.
> 
> tensorrt版本必须是7吗？

I used version 7.

**Comment by RizhaoCai** [comment]
Hey @zwqnju  and @longnanxi 

Thanks for your discussion.
You should check your created engine. If errors happen when building an engine, a None object will be returned. 
It has nothing to do with TensorRT version.

**Comment by huxianer** [comment]
> I think that I fix this issue. I fork @RizhaoCai 's project. My version is here: https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb
> I just modifed a few lines.

Hi,You just comment the module of int8,but the problem with int8 is not solved!

**Comment by RizhaoCai** [comment]
> > I think that I fix this issue. I fork @RizhaoCai 's project. My version is here: https://github.com/zwqnju/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb
> > I just modifed a few lines.
> 
> Hi,You just comment the module of int8,but the problem with int8 is not solved!

Hello huxianer,
What do you mean? This issue has nothing to do with int8.
Can you provide more information?

**Comment by Zhang-O** [comment]
Connected to pydev debugger (build 181.5540.34)
Loading ONNX file from path ./models/onnx/model.onnx...
Beginning ONNX file parsing
WARNING: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Successfully casted down to INT32.
Completed parsing of ONNX file
Building an engine from file ./models/onnx/model.onnx; this may take a while...
[TensorRT] ERROR: Network must have at least one output
Failed to create the engine

    onnx.py", line 440, in onnx2rt
    context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

Process finished with exit code 1
