### ISSUE TITLE
AdaptiveAvgPool2d not supported by tensorRT OnnxParser

### ISSUE THREAD

**Issue by xiaoxifei1223** [RizhaoCai/PyTorch_ONNX_TensorRT#4]
Env:
ubuntu 16.04 
Python 3.6
Pytorch 1.3.0
tensorRT:7.0.11

Detail:
the adaptiveavgpool2d operation is not supported by onnxparser, so it could lead to the failure of transformation of onnx to tensorrt.
you could use  
for error in range(parser.num_errors):
                        print(parser.get_error(error))
after the parser read onnx model

**Comment by RizhaoCai** [comment]
> Env:
> ubuntu 16.04
> Python 3.6
> Pytorch 1.3.0
> tensorRT:7.0.11
> 
> Detail:
> the adaptiveavgpool2d operation is not supported by onnxparser, so it could lead to the failure of transformation of onnx to tensorrt.
> you could use
> for error in range(parser.num_errors):
> print(parser.get_error(error))
> after the parser read onnx model


Hi， @xiaoxifei1223 
Thanks for sharing. This will help others.
