### ISSUE TITLE
Hi, I want to make sure whether there are any differences between engine generation by your python code and by trtexec? 

### ISSUE THREAD

**Issue by young169** [RizhaoCai/PyTorch_ONNX_TensorRT#5]
And I also want to know how to quantize it in int8 model rather than fp32 by trtexec, if this is familiar to you.

**Comment by young169** [comment]
> I have python3.6 and pytorch1.3.1 and tensorrt 7.0.0. Are these the possible reason for this error?
> ![image](https://user-images.githubusercontent.com/18310166/88354373-403f5380-cd93-11ea-949e-bfc7b813a69e.png)

I fixed this issue, but I still have problems on my own onnx model...

**Comment by RizhaoCai** [comment]
Hello,


According to the picture below, there is no difference.
![image](https://user-images.githubusercontent.com/37952703/89619833-3eac7a00-d8c1-11ea-99e6-bb01faf74f44.png)

For my side, I use trtexec mainly for debugging.
