### ISSUE TITLE
problems occured when executing "python trt_int8_demo.py "

### ISSUE THREAD

**Issue by Zhang-O** [RizhaoCai/PyTorch_ONNX_TensorRT#7]
Building an engine from file model_128.onnx; this may take a while...
Traceback (most recent call last):
  File "trt_int8_demo.py", line 138, in <module>
    main()
  File "trt_int8_demo.py", line 92, in main
    engine_int8 = trt_helper.get_engine(batch_size,onnx_model_path,engine_model_path, fp16_mode=False, int8_mode=True, calibration_stream=calibration_stream, save_engine=True)
  File "/data/zhangyl/PyTorch_ONNX_TensorRT/helpers/trt_helper.py", line 95, in get_engine
    return build_engine(max_batch_size, save_engine)
  File "/data/zhangyl/PyTorch_ONNX_TensorRT/helpers/trt_helper.py", line 76, in build_engine
    engine = builder.build_cuda_engine(network)
TypeError: read_calibration_cache() missing 1 required positional argument: 'length'

**Comment by RizhaoCai** [comment]
> Building an engine from file model_128.onnx; this may take a while...
> Traceback (most recent call last):
> File "trt_int8_demo.py", line 138, in
> main()
> File "trt_int8_demo.py", line 92, in main
> engine_int8 = trt_helper.get_engine(batch_size,onnx_model_path,engine_model_path, fp16_mode=False, int8_mode=True, calibration_stream=calibration_stream, save_engine=True)
> File "/data/zhangyl/PyTorch_ONNX_TensorRT/helpers/trt_helper.py", line 95, in get_engine
> return build_engine(max_batch_size, save_engine)
> File "/data/zhangyl/PyTorch_ONNX_TensorRT/helpers/trt_helper.py", line 76, in build_engine
> engine = builder.build_cuda_engine(network)
> TypeError: read_calibration_cache() missing 1 required positional argument: 'length'

Hello @Zhang-O 
The code runs well in my side, with the environment as described in the ReadMe file.

What environments (versions) are you using?
Are you using TensorRT 7?

**Comment by RizhaoCai** [comment]
> Building an engine from file model_128.onnx; this may take a while...
> Traceback (most recent call last):
> File "trt_int8_demo.py", line 138, in
> main()
> File "trt_int8_demo.py", line 92, in main
> engine_int8 = trt_helper.get_engine(batch_size,onnx_model_path,engine_model_path, fp16_mode=False, int8_mode=True, calibration_stream=calibration_stream, save_engine=True)
> File "/data/zhangyl/PyTorch_ONNX_TensorRT/helpers/trt_helper.py", line 95, in get_engine
> return build_engine(max_batch_size, save_engine)
> File "/data/zhangyl/PyTorch_ONNX_TensorRT/helpers/trt_helper.py", line 76, in build_engine
> engine = builder.build_cuda_engine(network)
> TypeError: read_calibration_cache() missing 1 required positional argument: 'length'

Hello @Zhang-O 
I notice that using TensorRT 7 (if you are using this) could have some problems with this code set (tested with TensorRT 5). But adapting the code to run is easy.

You can modify the code in helpers/trt_int8_calibration_helper.py (at line 35).
```python3
    def read_calibration_cache(self, length):
        # If there is a cache, use it instead of calibrating again. Otherwise, implicitly return None.
        if os.path.exists(self.cache_file):
            with open(self.cache_file, "rb") as f:
                return f.read()

```
to 
```python3
    def read_calibration_cache(self):
        # If there is a cache, use it instead of calibrating again. Otherwise, implicitly return None.
        if os.path.exists(self.cache_file):
            with open(self.cache_file, "rb") as f:
                return f.read()
```

and see how it works.


Cheers
