### ISSUE TITLE
Does onnx convert tensorRT need a data set for calibration?

### ISSUE THREAD

**Issue by cuixing158** [RizhaoCai/PyTorch_ONNX_TensorRT#9]
I saw some quantization tutorials stating that a small part of the training data set is required for quantitative calibration to determine the range of activation values for activation and weights. Why is there no such part in the code you provided, or is it unnecessary? Thank you

**Comment by RizhaoCai** [comment]
For FP321 and FP16 mode, there is no need of calibration.
However, the Int8 mode needs calibration.
If you check line 84 of trt_int8_demo.py, you will see there is data provided for calibration.
